### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by castamir** [lhellebr/PIS#4]
Chybí nám následující US pro

Řidič:
- najít a zobrazit řidičák + body
- zobrazit přestupky

Zaměstnanec (tj Policie + úředník):
- najít vozidlo - HOTOVO
- najít řidičák

Policie:
- zadat přestupek (odebrat body) - HOTOVO
- vrátit (přidat) body - HOTOVO
- krádež - nastavit + odebrat status "ukradeno" - HOTOVO

Úředník:
- registrace, změna, odhlášení vozidla - HOTOVO
- vydání a změna řidičáku - HOTOVO
- odebrání a vrácení řidičáku - HOTOVO

**Comment by roubalm** [comment]
Policie:
- zadat přestupek
- vrátit body

tohle je hotovo
